blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogList, BlogCreate, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogList.as_view(), name='blog'),
    path('create/', BlogCreate.as_view(), name='create'),
    path('view/<int:pk>/', BlogDetail.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdate.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('auth/', include('users_auth.urls', namespace='users_auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_auth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users_auth.apps import UsersAuthConfig
from users_auth.views import RegisterView, VerifyCodeView, PasswordResetView, reset_password

app_name = UsersAuthConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users_auth/login_form.html'), name='login'),
    path('', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    # path('pass_reset/', PasswordResetView.as_view(), name='pass_reset'),
    path('pass_reset/', reset_password, name='pass_reset'),
]

users_auth/models.py
import random

from django.contrib.auth.models import AbstractUser, Group
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='E-mail')
    phone = models.CharField(
        max_length=20,
        verbose_name='Номер телефона',
        **NULLABLE)
    avatar = models.ImageField(
        upload_to='avatars/',
        verbose_name='Аватар',
        **NULLABLE)
    country = models.CharField(
        max_length=50,
        verbose_name='Страна',
        **NULLABLE)

    code = ''.join([str(random.randint(0, 9)) for _ in range(6)])
    verify_code = models.CharField(
        max_length=6,
        default=code,
        verbose_name='Код вeрификации')
    is_verified = models.BooleanField(
        default=False, verbose_name='Верификация')

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions',
        blank=True,
        verbose_name='Custom user permissions',
        help_text='Specific permissions for this user.',
    )

    groups = models.ManyToManyField(
        Group,
        related_name='custom_user_groups',
        blank=True,
        verbose_name='Custom user groups',
        help_text='The groups this user belongs to.',
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from catalog.forms import StyleFormMixin
from users_auth.models import User


class RegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class NewPasswordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

users_auth/views.py
import random
import string

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import CreateView, FormView

from users_auth.forms import RegisterForm, NewPasswordForm
from users_auth.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('users_auth:verify_code')
    template_name = 'users_auth/registration_form.html'

    def form_valid(self, form):
        user = form.save()

        send_mail(
            subject='Регистрация на платформе',
            message=f"Код подтверждения: {user.verify_code}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email])
        return super().form_valid(form)


class VerifyCodeView(View):
    model = User
    template_name = 'users_auth/verifycode_form.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        user = User.objects.filter(verify_code=request.POST.get('verify_code')).first()
        if user:
            user.is_verified = True
            user.save()
            return redirect('users_auth:login')

        return redirect('users_auth:verify_code')


class PasswordResetView(FormView):
    template_name = 'users_auth/password_reset_form.html'
    form_class = NewPasswordForm
    success_url = reverse_lazy('user_auth:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        user = User.objects.get(email=email)

        pass_symbols = ''.join(random.choice(string.ascii_letters + string.digits + '!@#$%&'))
        password = get_random_string(12, pass_symbols)

        user.set_password(password)
        user.save()

        send_mail(
            subject='Пароль восстановлен',
            message=f'Ваш новый пароль: {password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.get(email=email)

        new_password = ''.join([random.choice(string.ascii_letters + string.digits + '!@#$%&') for _ in range(12)])

        send_mail(
            subject='Пароль восстановлен',
            message=f'Ваш новый пароль: {new_password}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        user.set_password(new_password)
        user.save()
        return redirect(reverse('users_auth:login'))
    else:
        form = NewPasswordForm
        context = {'form': form}
        return render(request, 'users_auth/password_reset_form.html', context)

users_auth/templates/users_auth/login_form.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<form class="row" method="post">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Войти</button>
                <a href="{% url 'users_auth:pass_reset' %}" class="btn btn-danger">Забыли пароль?</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users_auth/templates/users_auth/password_reset_form.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<form class="form-signin" method="post">
    <div class="col-6">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Создать новый пароль</h3>
            </div>
            <div class="card-body">
                {{ form }}
                <button type="submit" class="btn btn-success">Отправить пароль</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

users_auth/templates/users_auth/registration_form.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<div class="col-6">
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Регистрация</button>
            </form>
        </div>
        <div class="card-footer"></div>
    </div>
</div>
{% endblock %}

users_auth/templates/users_auth/verifycode_form.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<form class="row" method="post">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Введите код подтверждения</h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="text" name="verify_code" class="form-control" id="name" placeholder="Введите код" required>
                <button type="submit" class="btn btn-primary">Подтвердить</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}