blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogList, BlogCreate, BlogDetail, BlogUpdate, BlogDelete

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogList.as_view(), name='blog'),
    path('create/', BlogCreate.as_view(), name='create'),
    path('view/<int:pk>/', BlogDetail.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdate.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import IndexView, ContactsView, ProductView, ProductCreateView, ProductDetailView, \
    ProductDeleteView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product', ProductView.as_view(), name="product-detail"),
    path('create/', ProductCreateView.as_view(), name='product-create'),
    # path('view/<int:pk>/', ProductDetailView.as_view(), name='product-view'),
    path('view/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product-view'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product-delete'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product-update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('auth/', include('users_auth.urls', namespace='users_auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users_auth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users_auth.apps import UsersAuthConfig
from users_auth.views import RegisterView, VerifyCodeView, PasswordResetView, reset_password

app_name = UsersAuthConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users_auth/login_form.html'), name='login'),
    path('', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    # path('pass_reset/', PasswordResetView.as_view(), name='pass_reset'),
    path('pass_reset/', reset_password, name='pass_reset'),
]

catalog/models.py
from django.db import models
from django.utils import timezone

from config import settings

NULLABLE = {'blank': True, 'null': True}


# Create your models here.
class BaseModel(models.Model):
    """
    Абстрактная модель, предоставляющая поля для отслеживания даты создания
    и последнего изменения объекта.
    """
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата создания')
    changed = models.DateTimeField(
        auto_now=True,
        verbose_name='дата последнего изменения')

    class Meta:
        abstract = True


class Category(models.Model):
    """
    Модель категории товаров.
    """
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    ordering = ('title',)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    """
    Модель продукта.
    """
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(
        verbose_name='описание', blank=True, null=True)
    preview = models.ImageField(
        upload_to='products/',
        verbose_name='изображение',
        blank=True,
        null=True)
    category = models.ForeignKey(
        'catalog.Category',
        on_delete=models.CASCADE,
        verbose_name='категория',
        blank=True,
        null=True)
    price = models.IntegerField(
        verbose_name='цена за покупку')
    time_create = models.DateTimeField(
        default=timezone.now,
        verbose_name='дата создания')
    time_update = models.DateTimeField(
        auto_now=True,
        verbose_name='дата обновления')

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name='владелец', **NULLABLE)
    is_published = models.BooleanField(
        default=False,
        verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.title}: {self.description} - {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['pk']
        permissions = [('set_published', 'Can publish products'),]


class Version(models.Model):
    VERSION_CHOICES = ((True, 'активная'), (False, 'не активная'))

    product = models.ForeignKey(
        'catalog.Product',
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    version_number = models.IntegerField(
        default=1, blank=True, verbose_name='Номер версии')
    version_name = models.CharField(
        max_length=250, verbose_name='Название версии')
    is_current = models.BooleanField(
        choices=VERSION_CHOICES,
        verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.product} {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)  # сортировка по номеру версии

catalog/forms.py
from django import forms

from catalog.models import Product, Version

STOP_WORD = [
    'казино',
    'криптовалюта',
    'крипта',
    'биржа',
    'дешево',
    'бесплатно',
    'обман',
    'полиция',
    'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        # fields = '__all__'
        exclude = {'owner', 'is_published'}

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for word in STOP_WORD:
            if word in cleaned_data:
                raise forms.ValidationError(
                    'Это слово использовать недопустимо')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for word in STOP_WORD:
            if word in cleaned_data:
                raise forms.ValidationError(
                    'Это слово использовать недопустимо')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


class ModeratorProductForm(ProductForm, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
import re

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Product, Version


class IndexView(TemplateView):
    """
    Представление, отображающее главную страницу.

    Атрибуты:
    - template_name (str): Название шаблона для отображения представления.

    Методы:
    - get_context_data(self, **kwargs): Получает контекстные данные для отображения представления.
    """

    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        """
        Получает контекстные данные для отображения представления.

        Аргументы:
        - **kwargs: Дополнительные именованные аргументы.

        Возвращает:
        - dict: Словарь, содержащий контекстные данные.
        """
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Главная'
        context['objects_list'] = Product.objects.all()
        return context


class ContactsView(TemplateView):
    """
    Представление, отображающее страницу контактов.

    Атрибуты:
    - template_name (str): Название шаблона для отображения представления.

    Методы:
    - post(self, request, *args, **kwargs): Обрабатывает POST-запрос для отправки формы контактов.
    - get_context_data(self, **kwargs): Получает контекстные данные для отображения представления.
    """

    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        """
        Обрабатывает POST-запрос для отправки формы контактов.

        Аргументы:
        - request (HttpRequest): Объект HTTP-запроса.
        - *args: Дополнительные позиционные аргументы.
        - **kwargs: Дополнительные именованные аргументы.

        Возвращает:
        - HttpResponse: HTTP-ответ после обработки POST-запроса.
        """
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}): {message}')
        return self.render_to_response(self.get_context_data())

    def get_context_data(self, **kwargs):
        """
        Получает контекстные данные для отображения представления.

        Аргументы:
        - **kwargs: Дополнительные именованные аргументы.

        Возвращает:
        - dict: Словарь, содержащий контекстные данные.
        """
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Контакты'
        return context


class ProductView(ListView):
    """
    Этот класс представляет собой представление для отображения списка продуктов.

    Атрибуты:
        template_name (str): Имя шаблона, используемого для отображения представления.
        model (class): Класс модели, представляющий данные для отображения.

    Методы:
        get_context_data(self, **kwargs): Переопределяет метод в родительском классе для предоставления дополнительных данных контекста для отображения.
    """
    template_name = 'catalog/product.html'
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Товары'
        context['objects_list'] = Product.objects.all()
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.is_authenticated and not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user).order_by('-time_create')
        elif not self.request.user.is_authenticated:
            queryset = queryset.filter(is_published=True).order_by('-time_update')
        return queryset


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product


def is_valid_version(version):
    """Функция для проверки номера версии продукта"""
    pattern = r'^\d{1,2}\.\d{1,2}\.\d{1,2}$'
    return re.match(pattern, version) is not None


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_form_class(self):
        if not self.request.user.is_superuser and self.request.user.has_perm('catalog.set_published'):
            return ModeratorProductForm
        return ProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменение товара'
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context['formset'] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context['formset'] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            if formset.is_valid():
                actual_version_count = 0
                for f in formset:
                    num = f.cleaned_data.get('number')
                    if num and not is_valid_version(num):
                        form.add_error(None, "Версия должна быть формата Х.Х.Х или ХХ.ХХ.ХХ")
                        return self.form_invalid(form=form)

                    if f.cleaned_data.get('is_actual'):
                        actual_version_count += 1
                        if actual_version_count > 1:
                            form.add_error(None, "Вы можете выбрать только одну активную версию")
                            return self.form_invalid(form=form)

                formset.save()
        return super().form_valid(form)

    def handle_no_permission(self):
        raise Http404('У вас нет прав для изменения этого товара')


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.product-delete'

catalog/templates/catalog/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">

<head>
    {% block meta %}
        {% include 'catalog/includes/inc__meta.html' %}
    {% endblock %}

    {% block title %}
        <title>
            {{ page_title|title }}
        </title>
    {% endblock %}

    {% block css %}
        {% include 'catalog/includes/inc__style_css.html' %}
    {% endblock %}
</head>

<body>
    <main>
        <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 200px;">
            {% block main_menu %}
                {% include 'catalog/includes/inc__main_menu.html' %}
            {% endblock %}
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                    <strong>Пользователь</strong>
                </a>
                <div class="dropdown-menu">
                    {% if not user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'users_auth:login' %}">Вход</a>
                    <a class="dropdown-item" href="{% url 'users_auth:register' %}">Регистрация</a>
                    {% else %}
                    <a class="dropdown-item" href="">Профиль</a>
                    <a class="dropdown-item" href="{% url 'users_auth:logout' %}">Выход</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="b-example-divider"></div>

        <div class="container">
            {% block page_header %}

            {% endblock %}
<hr>
            {% block page_content %}

            {% endblock %}

            {% block page_footer %}
                {% include 'catalog/includes/inc__footer.html' %}
            {% endblock %}


            {% block script %}
                {% include 'catalog/includes/inc__script.html' %}
            {% endblock %}
        </div>
    </main>
</body>

</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block page_header %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Контакты</h1>
    </div>
</header>
{% endblock %}

{% block page_content %}
<main class="row">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block script %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block page_header %}
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Главная</h1>
        </div>
    </header>
{% endblock %}

{% block page_content %}
    <main class="row">
        <div class="row text-center">
            <div class="col-4">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Товар 1</h4>
                    </div>
                    <div class="card-body">
                        <h2 class="card-title pricing-card-title">$100</h2>
                        <p>
                            10 users included,
                            2 GB of storage,
                            Email support,
                            Help center access
                        </p>
                        <button type="button" class="btn btn-success">Купить</button>
                    </div>
                </div>
            </div>

            <div class="col-4">
                <form>
                    <div class="mb-3">
                        <label for="exampleInputName" class="form-label">Имя</label>
                        <input type="name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputEmail" class="form-label">Email</label>
                        <input type="email" class="form-control" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>



            <div class="row">
                <div class="col-6"></div>


                <div class="container">

                    <div class="card-header py-3">
                        <h1 class="my-0 fw-normal">FAQ</h1>
                    </div>

                    <p class="d-inline-flex gap-1">
                        <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button"
                            aria-expanded="false" aria-controls="multiCollapseExample1">Как
                            купить?</a>
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#multiCollapseExample2" aria-expanded="false"
                            aria-controls="multiCollapseExample2">Как доставить?</button>
                        <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#multiCollapseExample3" aria-expanded="false"
                            aria-controls="multiCollapseExample3">Какая гарантия?</button>
                    </p>
                    <div class="row">
                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample1">
                                <div class="card card-body">
                                    На сайте или в приложении
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample2">
                                <div class="card card-body">
                                    Почта России или самовывоз
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="collapse multi-collapse" id="multiCollapseExample3">
                                <div class="card card-body">
                                    Никакой
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load tags %}

{% block css %}
        {% include 'catalog/includes/inc__style_css.html' %}
<style>
    .catalog_product_box {
        padding-top: 30px;
        padding-bottom: 120px;
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
    }
</style>
{% endblock %}
{% block page_header %}
 <header>
     <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
         <h1 class="display-4 fw-normal text-body-emphasis">Каталог товаров</h1>
     </div>
 </header>
{% endblock %}

{% block page_content %}
<div class="catalog_product_box">
    <div class="col-12 mb-5">
        {% if user.is_verified %}
        <a class="btn btn-outline-primary" href="{% url 'catalog:product-create' %}">Добавить продукт</a>
        {% endif %}
    </div>
    {% for object in objects_list %}
    <div class="card mb-4 box-shadow" style="width: 620px;">
        <div class="card-header">
            <h4>{{ object.title }}</h4>
        </div>
        <div class="card-body">
            <div style="height: 200px; display: flex; justify-content: center; align-items: center;">
                <img src="{% mediapath object.preview %}" style="max-height: 100%; max-width: 100%; height: auto; width: auto;">
            </div>
            <h1 class="card-title pricing-card-title">{{ object.price }} ₽</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>Описание: {{ object.description|truncatechars:100 }}</li>
                <li>Категория: {{ object.category }}</li>
                <li>Создан: {{ object.created|date:"d.m.Y h:m" }}</li>
                <li>Изменен: {{ object.changed|date:"d.m.Y h:m" }}</li>
            </ul>
            <hr>
            <div class="d-flex justify-content-center align-items-center">
                <div class="btn-group">
                    <a type="button" class="btn btn-sm btn-outline-secondary btn-warning">В корзину</a>
                    <a href="{% url 'catalog:product-view' object.pk %}" type='button' class="btn btn-sm btn-outline-secondary">Просмотр</a>
                    {% if user.is_verified %}
                    {% if perms.catalog.change_product or user == object.owner %}
                    <a href="{% url 'catalog:product-update' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Редактирование</a>
                    {% endif %}
                    {% if perms.catalog.delete_product %}
                    <a href="{% url 'catalog:product-delete' object.pk %}" type='button' class="btn btn-sm btn-outline-danger">Удаление</a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.title }}"</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:product-detail' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block page_header %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">{{ object.title }}</h1>
    </div>
</header>
{% endblock %}

{% block page_content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Информация о продукте</h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Описание</td>
                            <td>{{ object.description }}</td>
                        </tr>
                        <tr>
                            <td>Категория</td>
                            <td>{{ object.category }}</td>
                        </tr>
                        <tr>
                            <td>Цена</td>
                            <td>{{ object.price }}</td>
                        </tr>
                        <tr>
                            <td>Владелец</td>
                            <td>{{ object.owner|default:"-" }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.preview }}" />
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block page_content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Добавление продукта</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        {% if formset %}
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Версии</h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}